// Ghidra 12.1.4 headless decompilation of FUN_80013698 (world projection) from disc\SLUS_009.74 ($payload stripped, base 0x80010000).
// Generated by DecompFunc.java; see docs/reverse/GHIDRA.md.

=== FUNCTION FUN_80013698 @ 80013698  body 80013698..80013ae3  
--- CALLERS ---  
--- CALLEES ---  
--- DECOMPILATION ---  

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_80013698(int param_1)

{
  int iVar1;
  int iVar2;
  short *psVar3;
  int *piVar4;
  int *piVar5;
  int iVar6;
  int iVar7;
  undefined4 *puVar8;
  int iVar9;
  undefined4 uVar10;
  uint uVar11;
  int iVar12;
  int iVar13;
  int iVar14;
  int iVar15;
  int iVar16;
  int iVar17;
  int iVar18;
  int iVar19;
  int iVar20;
  int iVar21;
  int iVar22;
  int iVar23;
  int iVar24;
  int iVar25;
  int iVar26;
  int iVar27;
  int iVar28;
  int local_18c [49];
  int local_c8;
  int local_c4;
  int local_c0;
  int local_b4;
  int local_b0;
  int local_ac;
  int local_64;
  int local_60;
  int local_5c;
  int local_58;
  int local_54;
  int local_50;
  
  iVar2 = *(int *)(*(int *)(_DAT_80099428 + 0x388) + 200);
  local_18c[0] = param_1;
  iVar22 = *(int *)(iVar2 + 0x88);
  iVar23 = *(int *)(iVar2 + 0x8c);
  iVar24 = *(int *)(iVar2 + 0x90);
  iVar12 = *(int *)(iVar2 + 0x6c);
  iVar13 = *(int *)(iVar2 + 0x70);
  iVar14 = *(int *)(iVar2 + 0x74);
  iVar15 = *(int *)(iVar2 + 0xdc);
  iVar16 = *(int *)(iVar2 + 0xe0);
  iVar17 = *(int *)(iVar2 + 0xe4);
  local_64 = *(int *)(iVar2 + 0xc0);
  local_60 = *(int *)(iVar2 + 0xc4);
  local_5c = *(int *)(iVar2 + 200);
  local_58 = *(int *)(iVar2 + 0x50);
  local_54 = *(int *)(iVar2 + 0x54);
  local_50 = *(int *)(iVar2 + 0x58);
  local_c8 = _DAT_80098b78;
  local_c4 = _DAT_80098b74;
  local_c0 = *(int *)(iVar2 + 0x40) >> 2;
  setCopControlWord(2,0xd000,400);
  puVar8 = (undefined4 *)&DAT_800a94e4;
  piVar5 = local_18c;
  iVar7 = 0;
  iVar20 = *(int *)(iVar2 + 0xa4);
  iVar21 = *(int *)(iVar2 + 0xa8);
  iVar2 = *(int *)(iVar2 + 0xac);
  while (iVar6 = iVar7, piVar4 = piVar5, -1 < iVar6) {
    psVar3 = (short *)*piVar4;
    iVar7 = iVar6 + -1;
    iVar18 = (int)*psVar3;
    iVar19 = (int)psVar3[1];
    piVar5 = piVar4 + -1;
    iVar27 = (int)psVar3[2];
    iVar25 = (int)psVar3[3];
    iVar26 = (int)psVar3[4];
    iVar28 = (int)psVar3[5];
    iVar9 = iVar27;
    if (-1 < iVar2) {
      iVar9 = iVar28;
    }
    iVar1 = iVar19;
    if (-1 < iVar21) {
      iVar1 = iVar26;
    }
    setCopReg(2,0x800,iVar9);
    iVar9 = iVar18;
    if (-1 < iVar20) {
      iVar9 = iVar25;
    }
    setCopReg(2,0,iVar1 * 0x10000 + iVar9);
    copFunction(2,0x180001);
    iVar9 = iVar27;
    if (-1 < iVar24) {
      iVar9 = iVar28;
    }
    iVar1 = iVar19;
    if (-1 < iVar23) {
      iVar1 = iVar26;
    }
    setCopReg(2,0x800,iVar9);
    iVar9 = iVar18;
    if (-1 < iVar22) {
      iVar9 = iVar25;
    }
    setCopReg(2,0,iVar1 * 0x10000 + iVar9);
    local_b4 = iVar20;
    local_b0 = iVar21;
    local_ac = iVar2;
    iVar9 = getCopReg(2,0x7000);
    copFunction(2,0x180001);
    if (-1 < iVar9 >> 0x10) {
      iVar9 = iVar27;
      if (-1 < iVar14) {
        iVar9 = iVar28;
      }
      iVar1 = iVar19;
      if (-1 < iVar13) {
        iVar1 = iVar26;
      }
      setCopReg(2,0x800,iVar9);
      iVar9 = iVar18;
      if (-1 < iVar12) {
        iVar9 = iVar25;
      }
      setCopReg(2,0,iVar1 * 0x10000 + iVar9);
      uVar10 = getCopReg(2,0x7000);
      copFunction(2,0x180001);
      if ((short)uVar10 - local_c4 < 1) {
        iVar9 = iVar27;
        if (-1 < iVar17) {
          iVar9 = iVar28;
        }
        iVar1 = iVar19;
        if (-1 < iVar16) {
          iVar1 = iVar26;
        }
        setCopReg(2,0x800,iVar9);
        iVar9 = iVar18;
        if (-1 < iVar15) {
          iVar9 = iVar25;
        }
        setCopReg(2,0,iVar1 * 0x10000 + iVar9);
        iVar9 = getCopReg(2,0x7000);
        copFunction(2,0x180001);
        if (-1 < iVar9 << 0x10) {
          iVar9 = iVar27;
          if (-1 < local_5c) {
            iVar9 = iVar28;
          }
          iVar1 = iVar19;
          if (-1 < local_60) {
            iVar1 = iVar26;
          }
          setCopReg(2,0x800,iVar9);
          iVar9 = iVar18;
          if (-1 < local_64) {
            iVar9 = iVar25;
          }
          setCopReg(2,0,iVar1 * 0x10000 + iVar9);
          uVar11 = getCopControlWord(2,0xf800);
          iVar9 = getCopReg(2,0xd800);
          copFunction(2,0x180001);
          if (((uVar11 & 0x400000) == 0) && (((iVar9 << 0x10) >> 2) - local_c0 < 1)) {
            if (-1 < local_50) {
              iVar27 = iVar28;
            }
            if (-1 < local_54) {
              iVar19 = iVar26;
            }
            setCopReg(2,0x800,iVar27);
            if (-1 < local_58) {
              iVar18 = iVar25;
            }
            setCopReg(2,0,iVar19 * 0x10000 + iVar18);
            iVar19 = getCopReg(2,0x7000);
            copFunction(2,0x180001);
            if (((iVar19 >> 0x10) - local_c8 < 1) &&
               (uVar11 = getCopControlWord(2,0xf800), iVar20 = local_b4, iVar21 = local_b0,
               iVar2 = local_ac, (uVar11 & 0x40000) == 0)) {
              if (*(int *)(psVar3 + 6) < 1) {
                if (*(int *)(psVar3 + 0xc) != 0) {
                  *piVar4 = *(int *)(psVar3 + 0xc);
                  piVar5 = piVar4;
                  iVar7 = iVar6;
                }
                if (*(int *)(psVar3 + 0x10) != 0) {
                  iVar7 = iVar7 + 1;
                  piVar5 = piVar5 + 1;
                  *piVar5 = *(int *)(psVar3 + 0x10);
                }
                if (*(int *)(psVar3 + 0xe) != 0) {
                  piVar5[1] = *(int *)(psVar3 + 0xe);
                  piVar5 = piVar5 + 1;
                  iVar7 = iVar7 + 1;
                }
              }
              else {
                *puVar8 = psVar3;
                puVar8 = puVar8 + 1;
              }
            }
          }
        }
      }
    }
  }
  setCopControlWord(2,0xd000,_DAT_80096974);
  _DAT_800a94e0 = (uint)(puVar8 + 0x1ffd5ac7) >> 2;
  _DAT_800aa484 = 0;
  return;
}

  